### ISSUE TITLE
Available ranks are S+ (over 10000), S (over 1000), A+ (over 500), A (over 100), B+ (over 50) and B (over 1).

### ISSUE THREAD

**Issue by kycasdzxc** [HwangTaehyun/github-contributor-stats#1]
Note: Available ranks are S+ (over 10000), S (over 1000), A+ (over 500), A (over 100), B+ (over 50) and B (over 1).

여기서 해당 랭크에 따른 점수 산정 기준이 어떻게 되는지 알 수 있을까요?

**Comment by HwangTaehyun** [comment]
안녕하세요! 기준은 레포가 받은 스타의 개수를 기준으로 산정했습니다. 사람들이 많이 사용하고 좋다고 생각하는 기준을 랭크의 기준으로 삼고 싶었습니다. 더 좋은 산정 기준 생각나시는거 있으면 이야기 해주세요!

**Comment by HwangTaehyun** [comment]
Discussion도 열었습니다. 혹시 또 궁금하신 내용 있으시거나 좋은 의견 있으시면 이야기 부탁드려요!
